site_name: "Portfolio de Milagros Cancela"
theme:
  name: material
  language: es
  features:
    - navigation.sections
    - navigation.indexes
  logo: assets/img/logo.png
  favicon: assets/img/logo.png
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Cambiar a oscuro
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Cambiar a claro
plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      fallback_to_build_date: true
  - glightbox
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true
extra_css:
  - css/extra.css
  - css/extra1.css